### ISSUE TITLE
Occugrid with problems

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#336] opened 2015-05-05 12:41 UTC
When I change an industry the viz is not building:
![image](https://cloud.githubusercontent.com/assets/6808970/7472617/b998ba00-f30a-11e4-8da9-822f870733cd.png)

If I change to EN, appear Internal Server Erro.
![image](https://cloud.githubusercontent.com/assets/6808970/7472632/db8e3bc6-f30a-11e4-90fc-6cffa57d2b64.png)

http://en.dataviva.info/apps/builder/occugrid/rais/4mg/c14126/all/cbo/?size=required&order=name&controls=true&year=2013

**Comment by davelandry** [comment] 2015-05-05 14:39
These are all related to the current server issues, duplicate of #335

**Closed by davelandry** 2015-05-05 14:39 UTC
