### ISSUE TITLE
Missing names in depth in Learn More section.

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#310] opened 2015-04-16 14:29 UTC
![image](https://cloud.githubusercontent.com/assets/6808970/7183087/b4386030-e42b-11e4-9725-8c25e2e2ce35.png)

http://dv2.datawheel.us/about/classification/bra/1/

**Comment by davelandry** [comment] 2015-04-16 16:21
Duplicate of #294 and will be fixed in today's update.

**Closed by davelandry** 2015-04-16 16:21 UTC
