### ISSUE TITLE
Stacked - Enrollment in a Major by Municipality 

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#327] opened 2015-04-29 12:16 UTC
States in Minas Gerais? Title and viz aren't correct. Both in PT and EN.
![image](https://cloud.githubusercontent.com/assets/6808970/7390593/293af0c2-ee50-11e4-8273-1a87dae0e1f1.png)
http://en.dataviva.info/apps/builder/stacked/hedu/4mg/all/380D01/bra/?y=enrolled&layout=value&order=color&controls=true&year=2009_2013

**Comment by davelandry** [comment] 2015-04-29 15:14
Duplicate of #326

**Closed by davelandry** 2015-04-29 15:14 UTC
Labels: Bug, Front-End
