### ISSUE TITLE
URGENT - Builder not working in PT

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#325] opened 2015-04-27 22:01 UTC
Guys, some people call me that builder is not working. I checked and see that this happened only in PT.
I can't change database in each visualization.

![screen shot 2015-04-27 at 19 46 29](https://cloud.githubusercontent.com/assets/6808970/7359707/0a33126a-ed18-11e4-8a6c-4d91f8148da3.png)

http://dataviva.info/apps/builder/tree_map/secex/4mg/all/all/hs/

Futhermore, appear a link below the filters.

@alexandersimoes and @davelandry look this!!!

**Comment by dgomes2004** [comment] 2015-04-28 13:31
Same as #323. It just happen if you are in PT. If you change to EN and then come back to PT, the builder works.

**Comment by davelandry** [comment] 2015-04-28 13:54
Closing this issue, as it is a duplicate of #323

**Closed by davelandry** 2015-04-28 13:54 UTC
Labels: Bug
