### ISSUE TITLE
Missing data in Line Graph

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#241] opened 2015-03-11 12:22 UTC
Looks like March of 2014 data is not on, could you check that? It happens in all others viz we checked. 
![image](https://cloud.githubusercontent.com/assets/6808970/6596154/3112afd4-c7d0-11e4-9e27-dfbd820be2f2.png)

**Comment by jspeis** [comment] 2015-03-11 14:15
Since I'm preparing the data for homologation testing, I would just add that it looks like we have the data in the database. If you check the call we make, http://dv2.datawheel.us/secex/all/all/178803.show.6/all/ it shows import/export values of 
123,099,819/47,687,228 for March 2014.

**Comment by eltonfreitas** [comment] 2015-03-11 14:27
Jonathan, I checked in Aliceweb (MIC site) and the values are equals for product 8803:

* Imports: 123.099.819
* Exports: 47.687.228

**Comment by davelandry** [comment] 2015-03-11 15:27
Confirmed to be fixed with the new version of D3plus. Will be part of this week's Thursday update.

**Closed by davelandry** 2015-03-11 15:27 UTC
Labels: Bug, Front-End
