### ISSUE TITLE
click for more info

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#248] opened 2015-03-11 17:37 UTC
When the more info box comes up, if you move the mouse, it goes away. So we can´t select anything.

**Comment by davelandry** [comment] 2015-03-11 18:53
Can you explain this in more depth? Which more info box, and what are you trying to select?

**Comment by davelandry** [comment] 2015-03-17 20:28
This is a duplicate of #254

**Closed by davelandry** 2015-03-17 20:28 UTC
Labels: Front-End
